### PR TITLE
refactor(dlint): use `try_for_each` instead of `for_each`

### PR DESCRIPTION
**Pull request by magurotuna**
This patch replaces `try_each` with `try_for_each` in `dlint`, which allows us to use `?` operator inside the closure. As a result, we can propagate errors from inside the closure to outside. The benefit of this is that we can remove `expect` calls on `Option` so that users will get a little bit user-friendly error messages with Rust's default panic messages removed, like:

```
Error: Unexpected token `)`. Expected this, import, async, function, [ for array literal, { for object literal, @ for decorator, function, class, null, true, false, number, bigint, string, regexp, ` for template literal, (, or an identifier at maguro.ts:3:4
```

For comparison, the previous error message looked like:

```
thread 'main' panicked at 'Failed to lint: SwcDiagnosticBuffer { diagnostics: ["Unexpected token `)`. Expected this, import, async, function, [ for array literal, { for object literal, @ for decorator, function, class, null, true, false, number, bigint, string, regexp, ` for template literal, (, or an identifier at maguro.ts:3:4"] }', examples/dlint/main.rs:203:8
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

This previous message had so much information that it might confuse the end users unnecessarily.

For reviewers, the diff looks clean with the whitespace diffs hidden: https://github.com/denoland/deno_lint/pull/754/files?diff=split&w=1

----

@lawrence-dol Does this fix meet your need described in #752? Your expectation contains a snippet where you can easily find the place with invalid syntax, but this patch doesn't do it. The change for this would require more rework, and I'm leaning towards putting it off.

### CODE REVIEW

**Review by bartlomieju — APPROVED** [review]
LGTM 🚀

**Comment by lawrence-dol** [comment]
@magurotuna : It's a significant improvement, but it would be much better if the format was closer to what I had suggested, if that's feasible. Particularly the line with the `filename:line:column` for editors to link the error to the source file.

```
Error: Unexpected token `)`. Expected this, import, async, function, [ for array literal, { for object literal, @ for decorator, function, class, null, true, false, number, bigint, string, regexp, ` for template literal, (, or an identifier.

  --> C:\...\maguro.ts:3:4
   |
 3 |     )}
   |     ^
   |
Found 1 problem
```

**Comment by magurotuna** [comment]
@lawrence-dol How about using `deno fmt --check`? It will output like

```
$ deno fmt --check maguro.ts
Error checking: /Users/yusuktan/Repos/github.com/magurotuna/deno_lint/maguro.ts
   Line 3, column 5: Unexpected token `)`. Expected this, import, async, function, [ for array literal, { for object literal, @ for decorator, function, class, null, true, false, number, bigint, string, regexp, ` for template literal, (, or an identifier

      )}
      ~
Checked 1 file
```

**Comment by lawrence-dol** [comment]
@magurotuna : That also emits all the things it doesn't like about the code formatting, which a large number of things in a minimized file 😆.

**Comment by lawrence-dol** [comment]
@magurotuna : I would like to see my suggested output format done eventually, but this is "good enough".

**Pull request merged**
