### PR TITLE
refactor docs to be rendered much better

### PR DESCRIPTION
**Pull request by magurotuna**
This PR refactors the existing documentation so that they are rendered much better in the terminal.

I looked through how they were rendered in the terminal, and I found:

- some of them were kind of poorly rendered because of extra whitespaces etc.
- some examples adopted unnecessarily inappropriate styles (for example using `var` without a good reason)

In this PR I fixed these things.

### CODE REVIEW

**Comment by bartlomieju** [comment]
@magurotuna this looks good to me, do you want to update more docs before landing?

**Comment by magurotuna** [comment]
@bartlomieju Yes, I'm gonna look through all the existing docs soon. I'll ping you when it's done :)

**Comment by magurotuna** [comment]
@bartlomieju Done, please take a look

**Review by bartlomieju — APPROVED** [review]
LGTM 🚀 

This is great @magurotuna 
Screenshot 2021-07-02 at 10 40 47

**Pull request merged**
