### PR TITLE
fix(prefer-primordials): Force `SafeArrayIterator` to be used for spread syntax in deno core

### PR DESCRIPTION
**Pull request by petamoriken**
Related https://github.com/denoland/deno_lint/issues/968

### CODE REVIEW

**Comment by petamoriken** [comment]
`spread_or_expr` handler isn't called. Does anyone who helps me exist?

**Comment by petamoriken** [comment]
`spread_or_expr` handler isn't called. Does anyone who helps me exist?

**Comment by petamoriken** [comment]
`spread_or_expr` handler isn't called. Does anyone who helps me exist?

**Comment by bartlomieju** [comment]
> `spread_or_expr` handler isn't called. Does anyone who helps me exist?

In this rule this handler is not overridden in any way so it just defaults to its base behavior. What is the expected bahavior in this case? If you add this handler manually can you see it being called?

**Comment by petamoriken** [comment]
> What is the expected bahavior in this case?

I want to detect Spread Syntax in Array Literal, Function Apply and Function Construct.

> If you add this handler manually can you see it being called?

It seems that the handler is not being called.

**Review by ia7ck — COMMENTED** [review]
@petamoriken 
To add a lint diagnostic when the parser visits an `ExprOrSpread` node, override the [`expr_or_spread`](https://github.com/denoland/deno_lint/blob/f963e0917835f20035818e032ba853d8a69cff10/src/handler.rs#L84) handler. 👍 

```rs
impl Handler for PreferPrimordialsHandler {
  
  // ...
  
  fn expr_or_spread(&mut self, expr_or_spread: &ast_view::ExprOrSpread, ctx: &mut Context) {
    if expr_or_spread.inner.spread.is_some() {
      ctx.add_diagnostic_with_hint(expr_or_spread.span(), CODE, MESSAGE, HINT);
    }
  }
}
```

**Comment by bartlomieju** [comment]
This looks great, I think it's useful. @lucacasonato any objections?

**Comment by petamoriken** [comment]
For `for-of`, I will create another PR.

**Pull request merged**
