### PR TITLE
[WIP] Refine explicit-function-return-type

### PR DESCRIPTION
**Pull request by magurotuna**
WORK IN PROGRESS

This fix is a part of #330, but this rule is not "recommended" rules, so I put it off; I'll work on recommended rules first.

Unfortunately, this rule seems more difficult to get compatible with the original one than I thought when I started to work - in fact, the original implementation is achieved using [a lot of helper functions](https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/src/util/explicitReturnTypeUtils.ts).
It indicates that we need to take care of many situations to implement this rule.

### CODE REVIEW

**Comment by Skillz4Killz** [comment]
Can we consider removing this rule entirely from the main deno lint rules please which are the default set of rules on `deno lint`? Leave this as something that can be added as a plugin. I've brought up the concerns with this rule before and how this rule is really a pain in the arse more than it is helpful and it also can cause infinite loop bugs because it hides errors that TS would catch. This rule encourages you to cast the return type thereby telling TS you know better. But 99% of the time, its the machine that knows better. As Ry said Deno should be easy and simple to use, so IMO the default `deno lint` should not include this which makes the dev experience worse. This should be added on by the end-user themself throught the plugin system. @bartlomieju @magurotuna 

image

**Comment by nayeemrmn** [comment]
> and it also can cause infinite loop bugs because it hides errors that TS would catch

@Skillz4Killz Nope, I remember clearly that you were wrong about that.

**Comment by Skillz4Killz** [comment]
> > and it also can cause infinite loop bugs because it hides errors that TS would catch
> 
> @Skillz4Killz Nope, I remember clearly that you were wrong about that.

I didn't want to continue the convo at the time since no one else felt it was desired to change the entire codebase in deno when it was already written but no I was not wrong nayeem. It does indeed hide the bug.

**Comment by bartlomieju** [comment]
> Can we consider removing this rule entirely from the main deno lint rules please which are the default set of rules on deno lint? 

This rule is not switched on in `deno lint`. Tested on `1.4.1`

**Comment by Skillz4Killz** [comment]
> > Can we consider removing this rule entirely from the main deno lint rules please which are the default set of rules on deno lint?
> 
> This rule is not switched on in `deno lint`. Tested on `1.4.1`

BEAUTIFUL! That's perfect!

**Comment by ry** [comment]
@magurotuna closing because old/stale.

**Pull request closed without merging**
