### PR TITLE
Light control flow graph and no-unreachable

### PR DESCRIPTION
**Pull request by kdy1**
cc @bartlomieju

I'll undraft this after handling labels

### CODE REVIEW

**Comment by kdy1** [comment]
@bartlomieju Can you re-run the workflows? It seems like rustc server gone down for a while

**Comment by bartlomieju** [comment]
@kdy1 done, I always use `git commit -m "reset CI" --allow-empty` to trigger CI run

**Comment by bartlomieju** [comment]
@kdy1 I just tested this rule on `deno/std/` unfortunately it yields a lot of false positives. 

Eg. this code:
```ts
export class Sha515 {
  // ...snip...

  arrayBuffer(): ArrayBuffer {
    this.finalize();
    const bits = this.#bits;
    const buffer = new ArrayBuffer(bits / 8);
    const dataView = new DataView(buffer);
    dataView.setUint32(0, this.#h0h);
    dataView.setUint32(4, this.#h0l);
    dataView.setUint32(8, this.#h1h);
    dataView.setUint32(12, this.#h1l);
    dataView.setUint32(16, this.#h2h);
    dataView.setUint32(20, this.#h2l);
    dataView.setUint32(24, this.#h3h);
    if (bits >= 256) {
      dataView.setUint32(28, this.#h3l);
    }
    if (bits >= 384) {
      dataView.setUint32(32, this.#h4h);
      dataView.setUint32(36, this.#h4l);
      dataView.setUint32(40, this.#h5h);
      dataView.setUint32(44, this.#h5l);
    }
    if (bits === 512) {
      dataView.setUint32(48, this.#h6h);
      dataView.setUint32(52, this.#h6l);
      dataView.setUint32(56, this.#h7h);
      dataView.setUint32(60, this.#h7l);
    }
    return buffer;
  }
}
```
produces:
```
(no-unreachable) This statement is unreachable
    this.finalize();
    ~~~~~~~~~~~~~~~~
    at /Users/biwanczuk/dev/deno/std/hash/sha512.ts:690:4

(no-unreachable) This statement is unreachable
    const bits = this.#bits;
    ~~~~~~~~~~~~~~~~~~~~~~~~
    at /Users/biwanczuk/dev/deno/std/hash/sha512.ts:691:4

(no-unreachable) This statement is unreachable
    const buffer = new ArrayBuffer(bits / 8);
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    at /Users/biwanczuk/dev/deno/std/hash/sha512.ts:692:4

(no-unreachable) This statement is unreachable
    const dataView = new DataView(buffer);
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    at /Users/biwanczuk/dev/deno/std/hash/sha512.ts:693:4

(no-unreachable) This statement is unreachable
    dataView.setUint32(0, this.#h0h);
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    at /Users/biwanczuk/dev/deno/std/hash/sha512.ts:694:4

(no-unreachable) This statement is unreachable
    dataView.setUint32(4, this.#h0l);
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    at /Users/biwanczuk/dev/deno/std/hash/sha512.ts:695:4

(no-unreachable) This statement is unreachable
    dataView.setUint32(8, this.#h1h);
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    at /Users/biwanczuk/dev/deno/std/hash/sha512.ts:696:4

(no-unreachable) This statement is unreachable
    dataView.setUint32(12, this.#h1l);
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    at /Users/biwanczuk/dev/deno/std/hash/sha512.ts:697:4

(no-unreachable) This statement is unreachable
    dataView.setUint32(16, this.#h2h);
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    at /Users/biwanczuk/dev/deno/std/hash/sha512.ts:698:4

(no-unreachable) This statement is unreachable
    dataView.setUint32(20, this.#h2l);
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    at /Users/biwanczuk/dev/deno/std/hash/sha512.ts:699:4

(no-unreachable) This statement is unreachable
    dataView.setUint32(24, this.#h3h);
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    at /Users/biwanczuk/dev/deno/std/hash/sha512.ts:700:4

(no-unreachable) This statement is unreachable
    if (bits >= 256) {
    ~~~~~~~~~~~~~~~~~~
    at /Users/biwanczuk/dev/deno/std/hash/sha512.ts:701:4

(no-unreachable) This statement is unreachable
    if (bits >= 384) {
    ~~~~~~~~~~~~~~~~~~
    at /Users/biwanczuk/dev/deno/std/hash/sha512.ts:704:4

(no-unreachable) This statement is unreachable
    if (bits === 512) {
    ~~~~~~~~~~~~~~~~~~~
    at /Users/biwanczuk/dev/deno/std/hash/sha512.ts:710:4

(no-unreachable) This statement is unreachable
    return buffer;
    ~~~~~~~~~~~~~~
    at /Users/biwanczuk/dev/deno/std/hash/sha512.ts:716:4
```

**Comment by kdy1** [comment]
Oh. I see. I'll fix it soon.

**Comment by kdy1** [comment]
I'm done.
Note that deno test suite contains 17 unreachable lines.

**Review by bartlomieju — APPROVED** [review]
LGTM, thank you @kdy1 this is massive PR that will help us move forward 🚀

**Pull request merged**
