### PR TITLE
feat: add no-import-assertions rule

### PR DESCRIPTION
**Pull request by petamoriken**
related: https://github.com/denoland/deno/issues/17944

### CODE REVIEW

**Comment by petamoriken** [comment]
Oh, we need to support dynamic imports

**Comment by petamoriken** [comment]
@magurotuna Please take a look!

**Review by dsherret — APPROVED** [review]
LGTM! Thanks for adding this.

**Comment by magurotuna** [comment]
Sorry I overlooked your notification @petamoriken, and thank you for reviewing David!

**Pull request merged**
