### PR TITLE
 Add getter-return and no-setter-return rules

### PR DESCRIPTION
**Pull request by eliassjogreen**

### CODE REVIEW

**Comment by bartlomieju** [comment]
@eliassjogreen thanks for contribution, could you rebase against master and add a test case?

**Comment by eliassjogreen** [comment]
Done!

**Comment by bartlomieju** [comment]
@eliassjogreen something went wrong during merge, there's a lot of code in diff that's already on `master`

**Comment by eliassjogreen** [comment]
Sorry, not that good at git yet. I will open a new pull request when i fixed it

**Pull request closed without merging**
