### PR TITLE
Add no-non-null-asserted-optional-chain rule

### PR DESCRIPTION
**Pull request by iykekings**

### CODE REVIEW

**Comment by divy-work** [comment]
@iykekings Are you still working on this?

**Comment by iykekings** [comment]
Yeah, will finish it before the week ends. Sorry for the delay

**Comment by iykekings** [comment]
There is just one test left to pass and it will be ready to be merged

**Comment by iykekings** [comment]
@bartlomieju this is ready to be merged. So sorry for the delay!

**Pull request merged**
