### PR TITLE
Add no-external-imports rule

### PR DESCRIPTION
**Pull request by hosseind88**
#944

### CODE REVIEW

**Comment by bartlomieju** [comment]
@hosseind88 @magurotuna I'm a bit confused by this rule. If I get this right, it disallows remote import in any file but `deps.ts`. What is the use case for that?

**Comment by bartlomieju** [comment]
Okay, sounds good. I agree that it shouldn't be in the "recommended" set

**Comment by hosseind88** [comment]
Hi guys, can we merge this? I see one failure in tests on ubuntu but I don't know why that is happening

**Comment by hosseind88** [comment]
aa right sorry forgot that, pushed now

**Review by bartlomieju — APPROVED** [review]
LGTM, thank you @hosseind88

**Pull request merged**
