### PR TITLE
feat: wasm-bindgen and stdweb compatbility

### PR DESCRIPTION
**Pull request by divy-work**
Uses wasm compatible `instant` instead of `std::instant`. Fall backs to `std::instant` when feature not specified.

Use cases for wasm compatibility - playground :smile:

### CODE REVIEW

**Comment by caspervonb** [comment]
Worth noting that std::time::Instant is supported with wasm32-wasi.

**Comment by divy-work** [comment]
Right, but not in `wasm32-unknown`

**Comment by lucacasonato** [comment]
> Worth noting that std::time::Instant is supported with wasm32-wasi

Does deno_lint compile with `wasm32-wasi`? If so I think this patch is not necessary. You can polyfill the `wasi_time_get ` syscall on the web using `Date` (or `performance.now()`).

**Comment by divy-work** [comment]
Got it.

**Comment by eliassjogreen** [comment]
This would be nice for wasm32-unknown-unknown support for a project the denosaurs are working on, I don't really see a reason why not to support it? wasm-pack (nor wasm-bindgen I think) doesn't seem to support wasi which makes the build process way more complicated and just a mess. If wasm32 support is not planned could you provide an example of how I would polyfill it?

**Comment by bartlomieju** [comment]
@eliassjogreen I'm not sure, CC @caspervonb

**Comment by caspervonb** [comment]
> I don't really see a reason why not to support it

I do, we should not be supporting ABIs that don't exist. Some of the cargo ecosystem have abused the target with feature flags but it is still a bare metal target with no system calls.

> wasm-pack (nor wasm-bindgen I think) doesn't seem to support wasi which makes the build process way more complicated and just a mess. 

They do, just compile with cargo build --target wasm32-wasi then run wasm-bindgen after without wasm-pack (wasm-pack is not a great tool IMO as it hides all the compilation steps from you).

**Comment by caspervonb** [comment]
Kom inn på Deno Discord om du sitter fast og trenger hjelp @eliassjogreen 🙃

**Pull request closed without merging**
