### PR TITLE
Adding valid-typeof Rule

### PR DESCRIPTION
**Pull request by DomParfitt**
Adds [https://eslint.org/docs/rules/valid-typeof](valid-typeof) rule as per #1.

@bartlomieju the ESLint version of this rule has an option - `requireStringLiterals` - that can be provided to it which acts like a strict-mode of sorts. For example, by default the rule will pick up the following as a lint error due to the misspelling of "undefined":
```javascript
typeof foo === "undefnied"
```
The correct version of the above code being:
```javascript
typeof foo === "undefined"
```
If the `requireStringLiterals` option is not set (or set to `false`) then the following code is also acceptable but is considered a lint error if `requireStringLiterals` is `true`:
```javascript
typeof foo === undefined
```
I have not implemented the functionality provided by `requireStringLiterals` as I don't think it's currently possible in `deno_lint` to provide options to rules and doing so probably falls out of the scope of implementing this particular rule.

### CODE REVIEW

**Comment by bartlomieju** [comment]
> Adds [https://eslint.org/docs/rules/valid-typeof](valid-typeof) rule as per #1.
> 
> @bartlomieju the ESLint version of this rule has an option - `requireStringLiterals` - that can be provided to it which acts like a strict-mode of sorts. For example, by default the rule will pick up the following as a lint error due to the misspelling of "undefined":
> 
> ```js
> typeof foo === "undefnied"
> ```
> 
> The correct version of the above code being:
> 
> ```js
> typeof foo === "undefined"
> ```
> 
> If the `requireStringLiterals` option is not set (or set to `false`) then the following code is also acceptable but is considered a lint error if `requireStringLiterals` is `true`:
> 
> ```js
> typeof foo === undefined
> ```
> 
> I have not implemented the functionality provided by `requireStringLiterals` as I don't think it's currently possible in `deno_lint` to provide options to rules and doing so probably falls out of the scope of implementing this particular rule.

@DomParfitt sounds good. There are currently no options, I for now I don't even consider adding them. If your solution uses more "strict" way of ESLint then I'm good with that :+1:

**Comment by DomParfitt** [comment]
@bartlomieju It currently implements the less strict version from ESLint (which I think is the default for ESLint) but it wouldn't take me much work for this rule to implement the stricter version as the default if you'd prefer.

**Comment by bartlomieju** [comment]
> @bartlomieju It currently implements the less strict version from ESLint (which I think is the default for ESLint) but it wouldn't take me much work for this rule to implement the stricter version as the default if you'd prefer.

Great, sounds good to me 👍

**Comment by DomParfitt** [comment]
@bartlomieju I've made the changes so the rule is now performing the stricter check if you want to re-check the code. 

The behaviour now is that it is only valid to compare a `typeof` with another `typeof` (i.e. `typeof foo === typeofbar`) or a specific set of strings (e.g. `"undefined"`, `"object"`, etc.).

**Pull request merged**
