### PR TITLE
Add no-fallthrough

### PR DESCRIPTION
**Pull request by kdy1**
I'll undraft this after ci passes.

### CODE REVIEW

**Comment by bartlomieju** [comment]
@kdy1 I think this is false positive, `default` is terminal anyway?
```
(no-fallthrough) Fallthrough is not allowed
    default: {
    ^^^^^^^^^^
      throw new Error(`Unrecognized file system flag: ${flag}`);
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    }
^^^^^
    at /Users/biwanczuk/dev/deno/std/node/_fs/_fs_common.ts:162:4
```

**Comment by bartlomieju** [comment]
Checked again and working as expected 👍  @kdy1 can we land already?

**Comment by kdy1** [comment]
I think so.

**Review by bartlomieju — APPROVED** [review]
LGTM 🚀

**Pull request merged**
