### PR TITLE
fix: no_self_assign - getter and private class member with same name

### LINKED ISSUE #1081: no_self_assign - getter and private class member with same name
Deno lint is flagging the snippet below with the `no_self_assign` rule.  It appears having a getter and a private class member with the same name (besides the `#` prefix) triggers the rule with Deno Lint.

### Lint Name
no_self_assign

### Code Snippet

```ts
class Foo {
    #bar = 1;

    constructor() {
        this.#bar = this.bar
    }

  get bar() {
    return 2
  }
}
```

### Expected Result

The above snippet should not trigger the `no_self_assign` rule.

### Actual Result

Deno Lint complains about `this.#bar = this.bar`.

### Additional Info

This [ESLint Playground example](https://eslint.org/play/#eyJ0ZXh0IjoiY2xhc3MgRm9vIHtcbiAgICAjYmFyID0gMTtcblxuICAgIGNvbnN0cnVjdG9yKCkge1xuICAgICAgICB0aGlzLiNiYXIgPSB0aGlzLmJhclxuICAgIH1cblxuICBnZXQgYmFyKCkge1xuICAgIHJldHVybiAyXG4gIH1cbn1cblxuY29uc29sZS5sb2cobmV3IEZvbygpLmJhcikiLCJvcHRpb25zIjp7InBhcnNlck9wdGlvbnMiOnsiZWNtYVZlcnNpb24iOiJsYXRlc3QiLCJzb3VyY2VUeXBlIjoic2NyaXB0IiwiZWNtYUZlYXR1cmVzIjp7fX0sInJ1bGVzIjp7ImNvbnN0cnVjdG9yLXN1cGVyIjpbImVycm9yIl0sImZvci1kaXJlY3Rpb24iOlsiZXJyb3IiXSwiZ2V0dGVyLXJldHVybiI6WyJlcnJvciJdLCJuby1hc3luYy1wcm9taXNlLWV4ZWN1dG9yIjpbImVycm9yIl0sIm5vLWNhc2UtZGVjbGFyYXRpb25zIjpbImVycm9yIl0sIm5vLWNsYXNzLWFzc2lnbiI6WyJlcnJvciJdLCJuby1jb21wYXJlLW5lZy16ZXJvIjpbImVycm9yIl0sIm5vLWNvbmQtYXNzaWduIjpbImVycm9yIl0sIm5vLWNvbnN0LWFzc2lnbiI6WyJlcnJvciJdLCJuby1jb25zdGFudC1jb25kaXRpb24iOlsiZXJyb3IiXSwibm8tY29udHJvbC1yZWdleCI6WyJlcnJvciJdLCJuby1kZWJ1Z2dlciI6WyJlcnJvciJdLCJuby1kZWxldGUtdmFyIjpbImVycm9yIl0sIm5vLWR1cGUtYXJncyI6WyJlcnJvciJdLCJuby1kdXBlLWNsYXNzLW1lbWJlcnMiOlsiZXJyb3IiXSwibm8tZHVwZS1lbHNlLWlmIjpbImVycm9yIl0sIm5vLWR1cGUta2V5cyI6WyJlcnJvciJdLCJuby1kdXBsaWNhdGUtY2FzZSI6WyJlcnJvciJdLCJuby1lbXB0eSI6WyJlcnJvciJdLCJuby1lbXB0eS1jaGFyYWN0ZXItY2xhc3MiOlsiZXJyb3IiXSwibm8tZW1wdHktcGF0dGVybiI6WyJlcnJvciJdLCJuby1leC1hc3NpZ24iOlsiZXJyb3IiXSwibm8tZXh0cmEtYm9vbGVhbi1jYXN0IjpbImVycm9yIl0sIm5vLWV4dHJhLXNlbWkiOlsiZXJyb3IiXSwibm8tZmFsbHRocm91Z2giOlsiZXJyb3IiXSwibm8tZnVuYy1hc3NpZ24iOlsiZXJyb3IiXSwibm8tZ2xvYmFsLWFzc2lnbiI6WyJlcnJvciJdLCJuby1pbXBvcnQtYXNzaWduIjpbImVycm9yIl0sIm5vLWlubmVyLWRlY2xhcmF0aW9ucyI6WyJlcnJvciJdLCJuby1pbnZhbGlkLXJlZ2V4cCI6WyJlcnJvciJdLCJuby1pcnJlZ3VsYXItd2hpdGVzcGFjZSI6WyJlcnJvciJdLCJuby1sb3NzLW9mLXByZWNpc2lvbiI6WyJlcnJvciJdLCJuby1taXNsZWFkaW5nLWNoYXJhY3Rlci1jbGFzcyI6WyJlcnJvciJdLCJuby1taXhlZC1zcGFjZXMtYW5kLXRhYnMiOlsiZXJyb3IiXSwibm8tbmV3LXN5bWJvbCI6WyJlcnJvciJdLCJuby1ub25vY3RhbC1kZWNpbWFsLWVzY2FwZSI6WyJlcnJvciJdLCJuby1vYmotY2FsbHMiOlsiZXJyb3IiXSwibm8tb2N0YWwiOlsiZXJyb3IiXSwibm8tcHJvdG90eXBlLWJ1aWx0aW5zIjpbImVycm9yIl0sIm5vLXJlZGVjbGFyZSI6WyJlcnJvciJdLCJuby1yZWdleC1zcGFjZXMiOlsiZXJyb3IiXSwibm8tc2VsZi1hc3NpZ24iOlsiZXJyb3IiXSwibm8tc2V0dGVyLXJldHVybiI6WyJlcnJvciJdLCJuby1zaGFkb3ctcmVzdHJpY3RlZC1uYW1lcyI6WyJlcnJvciJdLCJuby1zcGFyc2UtYXJyYXlzIjpbImVycm9yIl0sIm5vLXRoaXMtYmVmb3JlLXN1cGVyIjpbImVycm9yIl0sIm5vLXVuZGVmIjpbImVycm9yIl0sIm5vLXVuZXhwZWN0ZWQtbXVsdGlsaW5lIjpbImVycm9yIl0sIm5vLXVucmVhY2hhYmxlIjpbImVycm9yIl0sIm5vLXVuc2FmZS1maW5hbGx5IjpbImVycm9yIl0sIm5vLXVuc2FmZS1uZWdhdGlvbiI6WyJlcnJvciJdLCJuby11bnNhZmUtb3B0aW9uYWwtY2hhaW5pbmciOlsiZXJyb3IiXSwibm8tdW51c2VkLWxhYmVscyI6WyJlcnJvciJdLCJuby11bnVzZWQtdmFycyI6WyJlcnJvciJdLCJuby11c2VsZXNzLWJhY2tyZWZlcmVuY2UiOlsiZXJyb3IiXSwibm8tdXNlbGVzcy1jYXRjaCI6WyJlcnJvciJdLCJuby11c2VsZXNzLWVzY2FwZSI6WyJlcnJvciJdLCJuby13aXRoIjpbImVycm9yIl0sInJlcXVpcmUteWllbGQiOlsiZXJyb3IiXSwidXNlLWlzbmFuIjpbImVycm9yIl0sInZhbGlkLXR5cGVvZiI6WyJlcnJvciJdfSwiZW52Ijp7ImJyb3dzZXIiOnRydWV9fX0=) shows the code passes ESLint.

### Version

deno 1.25.3 (release, x86_64-pc-windows-msvc)
v8 10.6.194.5
typescript 4.7.4

### PR DESCRIPTION
**Pull request by hirasawayuki**
# Fixes #1081 
fix no_self_assign rule, when getter and private class member with same name.
`NoSelfAssignVisitor#are_same_property()` returns false, if the MemberExpr.prop is a pair of `MemberProp::Ident` and `MemberProp::PrivateName`.

### CODE REVIEW

**Review by magurotuna — APPROVED** [review]
LGTM, nice fix!

**Comment by magurotuna** [comment]
Seems like there's a partial outage on GHA. We'll wait for that to restore https://www.githubstatus.com/

**Comment by hirasawayuki** [comment]
I would delete [3fd21b8](https://github.com/denoland/deno_lint/pull/1084/commits/3fd21b82211e7f938d59824b56fb843777fecb0a) and [6b8684f](https://github.com/denoland/deno_lint/pull/1084/commits/6b8684fb624fbded72c2f33c26bbe7dc2ac87d01)  as they are unnecessary commits.

**Comment by magurotuna** [comment]
Nice 👍  JFYI we basically do "squash and merge" when merging PRs. So you don't really have to care about keeping the commits tidy.

**Comment by hirasawayuki** [comment]
> JFYI we basically do "squash and merge" when merging PRs. So you don't really have to care about keeping the commits tidy.

I got it! Thank you for comment!

**Pull request merged**
