### PR TITLE
fix: Update syntax hightlighting css file and set 100vh container

### PR DESCRIPTION
**Pull request by kamilogorek**
Fixes https://github.com/denoland/deno_lint/issues/1126

### Post

---

### CODE REVIEW

**Review by bartlomieju — APPROVED** [review]
Sweet! Thanks!

**Comment by not-my-profile** [comment]
Regarding the background color adding the `h-screen` class has actually had the reverse effect in Firefox. I now get a white background in Firefox (and removing the class fixes it).

**Comment by magurotuna** [comment]
@not-my-profile 
What you mean by "white background" is like this? This happens on all browsers I tried, including Chrome, Firefox, and Safari
image

**Comment by not-my-profile** [comment]
Yes like that. That doesn't happen on Chromium for me.

**Comment by IllusionPerdu** [comment]
I think h-screen sould be:
`.h-screen {
    height: 100%;
}`
and not 100vh because when the liste is more important than the screen height it's stopped the background after the height screen.

**Comment by not-my-profile** [comment]
Ah yeah thanks for pointing this out :) Opened #1133 to fix this.

**Pull request merged**
