### PR TITLE
Drop `LintRule::lint_program`

### PR DESCRIPTION
**Pull request by not-my-profile**
If you like these changes please merge them without squashing.

Note that the last of the three commits is strictly speaking a breaking API change but I'd assume that the `LintRule` API is only used internally.

### CODE REVIEW

**Comment by not-my-profile** [comment]
Let me know if you have questions :)

**Review by magurotuna — COMMENTED** [review]
Thanks for the cleanup! Though I'm not really sure if I understand correctly the benefit of this change. As I commented in the source code, the reason we keep `list_program` is because we need to support both `ProgramRef` (which references to swc's structs) and `Program` (which holds deno_ast's structs) while we are migrating to the latter. So having `lint_program` serves as a marker that indicates "this implementation should be replaced using deno_ast".
If you think of any other benefits this PR will bring, I'd be happy to hear :)

**Comment by not-my-profile** [comment]
The change firstly simplifies the `LintRule` trait by getting rid of an unnecessary method and secondly it gets rid of  `unreachable!();`. Idiomatic Rust code does not use `unreachable!();` since it leads to a runtime panic. Looking at the code the first time I was very much confused why there was `unreachable!()` everywhere ... it's certainly not good design.

> So having `lint_program` serves as a marker

You still have that marker ... now it's in the form of the `program_ref` function.

**Comment by magurotuna** [comment]
That makes sense, thanks for clarification!

**Review by magurotuna — APPROVED** [review]
LGTM

**Pull request merged**
